on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

name: Create Release

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
      major: ${{ steps.release-please.outputs.major }}
      minor: ${{ steps.release-please.outputs.minor }}
      patch: ${{ steps.release-please.outputs.patch }}
      sha: ${{ steps.release-please.outputs.sha }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: simple

  build:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    strategy:
      matrix:
        java-version: [21, 17, 16, 11, 8]

    name: Build ${{ matrix.java-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/anthonyporthouse/paper-server
          flavor: |
            prefix=java${{ matrix.java-version }}-
          tags: |
            type=semver,pattern={{version}},value=${{ needs.release-please.outputs.tag_name }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.release-please.outputs.tag_name }}
            type=semver,pattern={{major}},value=${{ needs.release-please.outputs.tag_name }}

            type=raw,value=latest,prefix=,enable=${{ matrix.java-version == 21 && 'true' || 'false' }}
            type=raw,value=latest
            type=raw,value=java${{ matrix.java-version }},prefix=

            type=sha
            type=sha,prefix=

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            JAVA_VERSION=${{matrix.java-version}}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
