name: Update Latest Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

permissions:
  packages: write

jobs:
  update-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [21, 17, 16, 11, 8]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Get Most Recent Tag"
        id: lastTag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.lastTag.outputs.tag }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/anthonyporthouse/paper-server
          flavor: |
            prefix=java${{ matrix.java-version }}-
          tags: |
            type=semver,pattern={{version}},value=${{ steps.lastTag.outputs.tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.lastTag.outputs.tag }}
            type=semver,pattern={{major}},value=${{ steps.lastTag.outputs.tag }}

            type=raw,value=latest,prefix=,enable=${{ matrix.java-version == 21 && 'true' || 'false' }}
            type=raw,value=latest
            type=raw,value=java${{ matrix.java-version }},prefix=

            type=sha
            type=sha,prefix=

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            JAVA_VERSION=${{matrix.java-version}}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
